application: domdori
version: 1
runtime: python
api_version: 1

handlers:
- url: /dns.*
  script: dns.py
- url: /domains.*
  script: domains.py
- url: /static
  static_dir: static
- url: .*
  script: main.py
